### ISSUE TITLE
Add Missing "with"

### ISSUE THREAD

**Issue by braughtg** [TestStu/OpenPace-VC-Walkthrough#29]
<a href="https://github.com/braughtg"><img src="https://avatars.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Wednesday Oct 13, 2021 at 12:23 GMT_
_Originally opened as https://github.com/braughtg/FarmData2-For190VC-Activities/issues/28_

----

Add the word "with" between "experiment" and "FarmData2" in the sentence "The FD2 Example tab is created by a sample module and can be used as a sandbox in which to learn about and experiment FarmData2 modules like those that produce the FieldKit and BarnKit tabs." at the end of the paragraph following the "FarmData2 Modules" heading in the README.md file **in the "farmdata2_modules/fd2_tabs/fd2_example" directory**.

**Comment by lpostner** [comment]
Lori Postner
